language: ruby
rvm:
  - 1.9.3
before_install:
  - sh .travis/install_riakcs.sh
before_script:
  - cp config.yml.example config.yml
script: rake test
notifications:
  email: false
  webhooks:
    urls:
      - http://hook-juggler.heroku.com/hooks/travis
    on_success: always
    on_failure: always
