language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
services:
  - redis-server
before_script:
  - cp config.yml.example.$BACKEND config.yml
  - mkdir -p tmp && echo "swifttoken" > tmp/swift_token.txt
script: ruby spec/$BACKEND/*
branches:
  only:
    - master
    - stable
notifications:
  email: false
  webhooks:
    urls:
      - http://hook-juggler.herokuapp.com/hooks/travis
    on_success: always
    on_failure: always
env:
  - BACKEND=s3
  - BACKEND=swift
# Run on Docker infrastructure
sudo: false
