language: ruby
cache: bundler
rvm:
  - 2.2.4
sudo: required
dist: trusty
before_install:
  - sh .travis/install_riakcs.sh
  - gem install bundler
before_script:
  - cp config.yml.example config.yml
script: bundle exec rake test
branches:
  only:
    - master
    - stable
notifications:
  email: false
  webhooks:
    urls:
      - http://hook-juggler.herokuapp.com/hooks/travis
    on_success: always
    on_failure: always
services:
  - riak
