language: ruby
rvm:
  - 1.9.2
  - 1.9.3
services: riak
before_script:
  - cp config.yml.example config.yml
script: rake test
notifications:
  webhooks:
    urls:
      - http://hook-juggler.heroku.com/hooks/travis
    on_success: change
    on_failure: always
