language: ruby
rvm:
  - 1.9.2
  - 1.9.3
services: riak
before_script:
  - cp config.yml.example config.yml
  - sudo cp .travis/app.config /etc/riak/
  - sudo service riak restart
script: rake test
notifications:
  webhooks:
    urls:
      - http://hook-juggler.heroku.com/hooks/travis
    on_success: always
    on_failure: always
