language: ruby
cache: bundler
rvm:
  - 2.2.6
services:
  - redis-server
before_install:
  - sh .travis/install_riakcs.sh
  - gem install bundler
before_script:
  - cp config.yml.example config.yml
  - mkdir -p tmp && echo "swifttoken" > tmp/swift_token.txt
script: ruby spec/swift/*
branches:
  only:
    - master
    - stable
notifications:
  email: false
  webhooks:
    urls:
      - http://hook-juggler.herokuapp.com/hooks/travis
    on_success: always
    on_failure: always
# Force legacy Blue Box build for now
sudo: required
group: legacy
