language: ruby
rvm:
  - 1.9.2
  - 1.9.3
services: riak
before_script:
  - cp config.yml.example config.yml
  - cat /etc/riak/app.config
  - sudo riak-admin status
  - sudo riak restart
script: rake test
notifications:
  webhooks:
    urls:
      - http://hook-juggler.heroku.com/hooks/travis
    on_success: always
    on_failure: always
